name: build

on:
  push:
    paths:
      - '.github/workflows/build-go.yml'
      - '.github/.version'
      - 'go-cuda_devel-ubuntu.Dockerfile'

jobs:

  build-go-cuda-devel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - run: make go-cuda-devel

